# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FirebaseFBLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseFBLogin
  pod 'FBSDKCoreKit', '4.35'
  pod 'FBSDKLoginKit', '4.35'
  pod 'FBSDKShareKit', '4.35'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Firebase/Auth'

end
